# Econometrics seminar

### Wooldridge
We are going to need data sets from wooldridge. [Click here](https://pypi.org/project/wooldridge/) for installation instructions

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

In [ ]:
import wooldridge

In [ ]:
wooldridge.data()

  J.M. Wooldridge (2019) Introductory Econometrics: A Modern Approach,
  Cengage Learning, 7th edition.

  401k       401ksubs    admnrev       affairs     airfare
  alcohol    apple       approval      athlet1     athlet2
  attend     audit       barium        beauty      benefits
  beveridge  big9salary  bwght         bwght2      campus
  card       catholic    cement        census2000  ceosal1
  ceosal2    charity     consump       corn        countymurders
  cps78_85   cps91       crime1        crime2      crime3
  crime4     discrim     driving       earns       econmath
  elem94_95  engin       expendshares  ezanders    ezunem
  fair       fertil1     fertil2       fertil3     fish
  fringe     gpa1        gpa2          gpa3        happiness
  hprice1    hprice2     hprice3       hseinv      htv
  infmrt     injury      intdef        intqrt      inven
  jtrain     jtrain2     jtrain3       jtrain98    kielmc
  labsup     lawsch85    loanapp       lowbrth     mathpnl
  meap00_01  meap01      meap93        meapsingle  minwage
  mlb1       mroz        murder        nbasal      ncaa_rpi
  nyse       okun        openness      pension     phillips
  pntsprd    prminwge     prison        rdchem      rdtelec
  recid      rental      return        saving      school93_98
  sleep75    slp75_81    smoke         traffic1    traffic2
  twoyear    volat       vote1         vote2       voucher
  wage1      wage2       wagepan       wageprc     wine

1. Use the data in [WAGE1.RAW](#get_wage1) for this exercise.

    1. Find the [average education](#average) level in the sample. [What are the lowest and highest years of education?](#max_min)
    2. [Find the average hourly wage in the sample](#av_hour_wage). Does it seem high or low?
    3. The wage data are reported in 1976 dollars. Using the Economic Report of the President (2011 or later), obtain and report the Consumer Price Index (CPI) for the years 1976 and 2010.
    4. Use the CPI values from part (iii) to find the average hourly wage in 2010 dollars. Now does the average hourly wage seem reasonable? How many women are in the sample? How many men?


<p id="get_wage1">Downloading WAGE1 data.</p>

In [ ]:
wooldridge.data('wage1', description=True)

name of dataset: wage1
no of variables: 24
no of observations: 526

+----------+---------------------------------+
| variable | label                           |
+----------+---------------------------------+
| wage     | average hourly earnings         |
| educ     | years of education              |
| exper    | years potential experience      |
| tenure   | years with current employer     |
| nonwhite | =1 if nonwhite                  |
| female   | =1 if female                    |
| married  | =1 if married                   |
| numdep   | number of dependents            |
| smsa     | =1 if live in SMSA              |
| northcen | =1 if live in north central U.S |
| south    | =1 if live in southern region   |
| west     | =1 if live in western region    |
| construc | =1 if work in construc. indus.  |
| ndurman  | =1 if in nondur. manuf. indus.  |
| trcommpu | =1 if in trans, commun, pub ut  |
| trade    | =1 if in wholesale or retail    |
| services | =1 if in services indus.        |
| profserv | =1 if in prof. serv. indus.     |
| profocc  | =1 if in profess. occupation    |
| clerocc  | =1 if in clerical occupation    |
| servocc  | =1 if in service occupation     |
| lwage    | log(wage)                       |
| expersq  | exper^2                         |
| tenursq  | tenure^2                        |
+----------+---------------------------------+

These are data from the 1976 Current Population Survey, collected by
Henry Farber when he and I were colleagues at MIT in 1988.

In [ ]:
df = wooldridge.data('wage1')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 526 entries, 0 to 525
Data columns (total 24 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   wage      526 non-null    float64
 1   educ      526 non-null    int64
 2   exper     526 non-null    int64
 3   tenure    526 non-null    int64
 4   nonwhite  526 non-null    int64
 5   female    526 non-null    int64
 6   married   526 non-null    int64
 7   numdep    526 non-null    int64
 8   smsa      526 non-null    int64
 9   northcen  526 non-null    int64
 10  south     526 non-null    int64
 11  west      526 non-null    int64
 12  construc  526 non-null    int64
 13  ndurman   526 non-null    int64
 14  trcommpu  526 non-null    int64
 15  trade     526 non-null    int64
 16  services  526 non-null    int64
 17  profserv  526 non-null    int64
 18  profocc   526 non-null    int64
 19  clerocc   526 non-null    int64
 20  servocc   526 non-null    int64
 21  lwage     526 non-null    float64
 22  expersq   526 non-null    int64
 23  tenursq   526 non-null    int64
dtypes: float64(2), int64(22)
memory usage: 98.8 KB

In [ ]:
df

,wage,educ,exper,tenure,nonwhite,female,married,numdep,smsa,northcen,...,trcommpu,trade,services,profserv,profocc,clerocc,servocc,lwage,expersq,tenursq
0,3.10,11,2,0,0,1,0,2,1,0,...,0,0,0,0,0,0,0,1.131402,4,0
1,3.24,12,22,2,0,1,1,3,1,0,...,0,0,1,0,0,0,1,1.175573,484,4
2,3.00,11,2,0,0,0,0,2,0,0,...,0,1,0,0,0,0,0,1.098612,4,0
3,6.00,8,44,28,0,0,1,0,1,0,...,0,0,0,0,0,1,0,1.791759,1936,784
4,5.30,12,7,2,0,0,1,1,0,0,...,0,0,0,0,0,0,0,1.667707,49,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
521,15.00,16,14,2,0,1,1,2,0,0,...,0,0,0,1,1,0,0,2.708050,196,4
522,2.27,10,2,0,0,1,0,3,0,0,...,0,1,0,0,1,0,0,0.819780,4,0
523,4.67,15,13,18,0,0,1,3,0,0,...,0,0,0,0,1,0,0,1.541159,169,324
524,11.56,16,5,1,0,0,1,0,0,0,...,0,0,0,0,0,0,0,2.447551,25,1
525,3.50,14,5,4,1,1,0,2,0,0,...,0,0,0,1,0,1,0,1.252763,25,16

<p id="average"><b>1.A</b></p> Use the data in WAGE1.RAW for this exercise

In [ ]:
df.educ.describe()

count    526.000000
mean      12.562738
std        2.769022
min        0.000000
25%       12.000000
50%       12.000000
75%       14.000000
max       18.000000
Name: educ, dtype: float64

In [ ]:
print(f"Lowest year of education: {df.educ.min()}")

Lowest year of education: 0

In [ ]:
print(f"Highest year of education: {df.educ.max()}")

Highest year of education: 18

<p id="av_hour_wage"><b>1.B</b></p>
Find the average hourly wage in the sample. Does it seem high or low?

In [ ]:
print(f"The average hourly wage in the sample: {df.wage.mean().round(2)}")

The average hourly wage in the sample: 5.9

2. Use the data in [BWGHT.RAW](#BWGHT.RAW) to answer this question
    1. How many [women are in the sample](#wom_in_sm), and how many report [smoking during pregnancy](#smok_dr_pr)?
    2. What is the [average number of cigarettes smoked per day](#av_p_d)? Is the average a good measure of the “typical” woman in this case? Explain.
    3. Among women who smoked during pregnancy, what is the [average number of cigarettes smoked per day](#ave_nm_sm_per_da)? How does this compare with your answer from part (ii), and why?
    4. Find the [average of fatheduc](#av_fath_ed) in the sample. Why are only 1,192 observations used to compute this average?
    5. Report the average family income and its standard deviation in dollars.

<p id='BWGHT.RAW'><b>2.</b></p>
Use the data in BWGHT.RAW to answer this question

In [ ]:
# Dataset Info
wooldridge.data('bwght', description=True)

name of dataset: bwght
no of variables: 14
no of observations: 1388

+----------+--------------------------------+
| variable | label                          |
+----------+--------------------------------+
| faminc   | 1988 family income, $1000s     |
| cigtax   | cig. tax in home state, 1988   |
| cigprice | cig. price in home state, 1988 |
| bwght    | birth weight, ounces           |
| fatheduc | father's yrs of educ           |
| motheduc | mother's yrs of educ           |
| parity   | birth order of child           |
| male     | =1 if male child               |
| white    | =1 if white                    |
| cigs     | cigs smked per day while preg  |
| lbwght   | log of bwght                   |
| bwghtlbs | birth weight, pounds           |
| packs    | packs smked per day while preg |
| lfaminc  | log(faminc)                    |
+----------+--------------------------------+

J. Mullahy (1997), “Instrumental-Variable Estimation of Count Data
Models: Applications to Models of Cigarette Smoking Behavior,” Review
of Economics and Statistics 79, 596-593. Professor Mullahy kindly
provided the data. He obtained them from the 1988 National Health
Interview Survey.

In [ ]:
df = wooldridge.data('bwght')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1388 entries, 0 to 1387
Data columns (total 14 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   faminc    1388 non-null   float64
 1   cigtax    1388 non-null   float64
 2   cigprice  1388 non-null   float64
 3   bwght     1388 non-null   int64
 4   fatheduc  1192 non-null   float64
 5   motheduc  1387 non-null   float64
 6   parity    1388 non-null   int64
 7   male      1388 non-null   int64
 8   white     1388 non-null   int64
 9   cigs      1388 non-null   int64
 10  lbwght    1388 non-null   float64
 11  bwghtlbs  1388 non-null   float64
 12  packs     1388 non-null   float64
 13  lfaminc   1388 non-null   float64
dtypes: float64(9), int64(5)
memory usage: 151.9 KB

<p id="wom_in_sm"><b>2.A</b></p>
How many women are in the sample, and how many report smoking during pregnancy?

In [ ]:
df

,faminc,cigtax,cigprice,bwght,fatheduc,motheduc,parity,male,white,cigs,lbwght,bwghtlbs,packs,lfaminc
0,13.5,16.5,122.300003,109,12.0,12.0,1,1,1,0,4.691348,6.8125,0.0,2.602690
1,7.5,16.5,122.300003,133,6.0,12.0,2,1,0,0,4.890349,8.3125,0.0,2.014903
2,0.5,16.5,122.300003,129,NaN,12.0,2,0,0,0,4.859812,8.0625,0.0,-0.693147
3,15.5,16.5,122.300003,126,12.0,12.0,2,1,0,0,4.836282,7.8750,0.0,2.740840
4,27.5,16.5,122.300003,134,14.0,12.0,2,1,1,0,4.897840,8.3750,0.0,3.314186
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1383,27.5,30.0,138.300003,110,12.0,12.0,4,1,1,0,4.700480,6.8750,0.0,3.314186
1384,5.5,30.0,138.300003,146,NaN,16.0,2,1,1,0,4.983607,9.1250,0.0,1.704748
1385,65.0,8.0,118.599998,135,18.0,16.0,2,0,1,0,4.905275,8.4375,0.0,4.174387
1386,27.5,8.0,118.599998,118,NaN,14.0,2,0,1,0,4.770685,7.3750,0.0,3.314186
1387,37.5,8.0,118.599998,111,16.0,13.0,2,0,1,0,4.709530,6.9375,0.0,3.624341

In [ ]:
len(df)

1388

In [ ]:
df.loc[df['cigs']>0]

,faminc,cigtax,cigprice,bwght,fatheduc,motheduc,parity,male,white,cigs,lbwght,bwghtlbs,packs,lfaminc
22,15.5,16.5,122.300003,129,8.0,11.0,2,1,1,6,4.859812,8.0625,0.30,2.740840
63,0.5,15.0,125.599998,104,NaN,12.0,2,0,0,10,4.644391,6.5000,0.50,-0.693147
68,7.5,21.0,127.699997,119,12.0,10.0,2,1,0,20,4.779123,7.4375,1.00,2.014903
74,18.5,21.0,127.699997,115,3.0,12.0,1,0,0,40,4.744932,7.1875,2.00,2.917771
92,7.5,21.0,127.699997,93,14.0,12.0,1,1,0,10,4.532599,5.8125,0.50,2.014903
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1348,32.5,30.0,138.300003,124,10.0,11.0,2,1,1,20,4.820282,7.7500,1.00,3.481240
1359,12.5,30.0,138.300003,119,12.0,12.0,3,0,1,3,4.779123,7.4375,0.15,2.525729
1361,5.5,30.0,138.300003,115,NaN,11.0,2,0,0,10,4.744932,7.1875,0.50,1.704748
1367,12.5,30.0,138.300003,130,16.0,14.0,1,1,1,15,4.867535,8.1250,0.75,2.525729
1375,17.5,30.0,138.300003,102,11.0,10.0,2,1,1,20,4.624973,6.3750,1.00,2.862201

In [ ]:
print(df.loc[df['cigs']>0]['cigs'].count())

212

<p id="av_p_d"><b>2.B</b></p>
What is the average number of cigarettes smoked per day? Is the average a good measure of the “typical” woman in this case? Explain.

In [ ]:
print(df.cigs.mean().round(3))

2.087

<p id="av_p_d"><b>2.C</b></p> Among women who smoked during pregnancy, what is the average number of cigarettes smoked per day? How does this compare with your answer from part, and why?

In [ ]:
print(df.loc[df['cigs']>0]['cigs'].mean().round(3))

13.665

<p id="av_fath_ed"><b>2.D</b></p>
Find the average of fatheduc in the sample. Why are only 1,192 observations used to compute this average?

In [ ]:
print(f"The average of fatheduc is {df.fatheduc.mean().round(3)}")

The average of fatheduc is 13.186

3. The data in [MEAP01.RAW](#df_meap) are for the state of Michigan in the year 2001. Use these data to answer the following questions.
    1. Find the [largest and smallest values of math4](#lar_sm_val). Does the range make sense? Explain.
    2. How many schools have a [perfect pass](#perf_pass) rate on the math test? What percentage is this of the total sample?
    3. How many schools have math pass [rates of exactly 50%](#50%)?
    4. Compare the average pass rates for the math and [reading scores](#reading_score). Which test is harder to pass?
    5. Find the [correlation between math4 and read4](#corr_math4_read4). What do you conclude?
    6. The variable exppp is expenditure per pupil. Find the [average of exppp](#aver_of_expp) alongwith its standard deviation. Would you say there is wide variation in per pupil spending?
    7. Suppose School A spends $\$6,000$ per student and School B spends $\$5,500$ per student. By what [percentage](#percentage) does School A’s spending exceed School B’s? Compare this to $100\cdot [\log(6,000) – \log(5,500)]$, which is the approximation percentage difference based on the difference in the natural logs. (See Section A.4 in Appendix A.)

<p id="df_meap"><b>3</b></p>
The data in MEAP01.RAW are for the state of Michigan in the year 2001. Use these data data to answer the following questions.

In [ ]:
wooldridge.data('meap01', description=True)

name of dataset: meap01
no of variables: 11
no of observations: 1823

+----------+-----------------------------------------------+
| variable | label                                         |
+----------+-----------------------------------------------+
| dcode    | district code                                 |
| bcode    | building code                                 |
| math4    | % students satisfactory, 4th grade math       |
| read4    | % students satisfactory, 4th grade reading    |
| lunch    | % students eligible for free or reduced lunch |
| enroll   | school enrollment                             |
| expend   | total spending, $                             |
| exppp    | expenditures per pupil: expend/enroll         |
| lenroll  | log(enroll)                                   |
| lexpend  | log(expend)                                   |
| lexppp   | log(exppp)                                    |
+----------+-----------------------------------------------+

Michigan Department of Education, www.michigan.gov/mde

In [ ]:
df = wooldridge.data('meap01')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1823 entries, 0 to 1822
Data columns (total 11 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   dcode    1823 non-null   float64
 1   bcode    1823 non-null   int64
 2   math4    1823 non-null   float64
 3   read4    1823 non-null   float64
 4   lunch    1823 non-null   float64
 5   enroll   1823 non-null   int64
 6   expend   1823 non-null   float64
 7   exppp    1823 non-null   float64
 8   lenroll  1823 non-null   float64
 9   lexpend  1823 non-null   float64
 10  lexppp   1823 non-null   float64
dtypes: float64(9), int64(2)
memory usage: 156.8 KB

<p id="larg_smal_val"><b>3</b></p>
Find the largest and smallest values of math4. Does the range make sense? Explain

In [ ]:
print(f"Largest value of math4 is {df['math4'].max()}, smallest value of math4 is {df['math4'].min()}")

Largest value of math4 is 100.0, smallest value of math4 is 0.0

<p id="perf_pass"><b>3.A</b></p>
How many schools have a perfect pass rate on the math test? What percentage is this of the total sample?

In [ ]:
print(f"There are {df['math4'].loc[df['math4']>=90].count()} schools with a perfect pass rate on the math test ")

There are 333 schools with a perfect pass rate on the math test

<p id="perf_pass"><b>3.B</b></p>
What percentage is this of the total sample?

In [ ]:
print(f"The percentage of the total sample {df['math4'].loc[df['math4']>=90].count()/df['math4'].count()*100}")

The percentage of the total sample 18.266593527153045

<p id="50%"><b>3.C</b></p>
How many schools have math pass rates of exactly 50%?

In [ ]:
print(f"There are {df['math4'].loc[df['math4']==50].count()} schools with math pass rates of exactly 50%")

There are 17 schools with math pass rates of exactly 50%

<p id="reading_score"><b>3.D</b></p>
Compare the average pass rates for the math and reading scores. Which test is harder to pass?

In [ ]:
print(f"Average pass rates math {df['math4'].mean().round(3)}.")
print(f"Average pass rates reading scores {df['read4'].mean().round(3)}")

Average pass rates math 71.909.
Average pass rates reading scores 60.062

<p id="corr_math4_read4"><b>3.E</b></p>
Find the correlation between math4 and read4. What do you conclude?

In [ ]:
print(f"Correlation matrix between math4 and read4 is \n {df[['math4','read4']].corr()}")

Correlation matrix between math4 and read4 is
           math4     read4
math4  1.000000  0.842728
read4  0.842728  1.000000

<p id="aver_of_expp"><b>3.F</b></p>
The variable exppp is expenditure per pupil. Find the average of exppp along with its standard deviation. Would you say there is wide variation in per pupil spending?

In [ ]:
print(f"Average expenditure per pupil is {df.exppp.mean().round(3)}")

Average expenditure per pupil is 5194.865

<p id="percentage"><b>3.G</b></p>
Suppose School A spends $\$6,000$ per student and School B spends $\$5,500$ per student. By what percentage does School A’s spending exceed School B’s? Compare this to $100\cdot [\log(6,000) – \log(5,500)]$, which is the approximation percentage difference based on the difference in the natural logs. (See Section A.4 in Appendix A.)


4. The data in JTRAIN2.RAW come from a job training experiment conducted for low-income men during $1976–1977$; see LaLonde $(1986)$.
    1. Use the indicator variable train to determine the fraction of men receiving job training.
    2. The variable re78 is earnings from $1978$, measured in thousands of $1982$ dollars. Find the averages of re78 for the sample of men receiving job training and the sample not receiving job training. Is the difference economically large?
    3. The variable unem78 is an indicator of whether a man is unemployed or not in $1978$. What fraction of the men who received job training are unemployed? What about for men who did not receive job training? Comment on the difference.
    4. From parts (ii) and (iii), does it appear that the job training program was effective? What would make our conclusions more convincing?

5. The data in FERTIL2.DTA were collected on women living in the Republic of Botswana in $1988$. The variable children refers to the number of living children. The variable electric is a binary indicator equal to one if the woman’s home has electricity, and zero if not.
    1. Find the smallest and largest values of children in the sample. What is the average of children?
    2. What percentage of women have electricity in the home?
    3. Compute the average of children for those without electricity and do the same for those with electricity. Comment on what you find.
    4. From part (iii), can you infer that having electricity “causes” women to have fewer children? Explain.

<p id="detailed-explanation">Обратите внимание, это важно.</p>